CREATE TABLE IF NOT EXISTS TODO_TASK("ID" BIGINT NOT NULL,
    "CHECKED" BOOLEAN NOT NULL,
    "CREATED_AT" TIMESTAMP,
    "DESCRIPTION" VARCHAR(255),
    "LAST_UPDATED" TIMESTAMP,
    "TITLE" VARCHAR(255),
    "USER_ID" BIGINT,
    "USER_NAME" VARCHAR(255));
 